//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentsWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facilities
    {
        public facilities()
        {
            this.equipment = new HashSet<equipment>();
        }
    
        public string Name { get; set; }
        public string IP { get; set; }
        public string Location_Address { get; set; }
        public int Location_Postcode { get; set; }
        public string Location_Country_CountryName { get; set; }
        public string UserAccounts_Email { get; set; }
    
        public virtual location location { get; set; }
        public virtual useraccounts useraccounts { get; set; }
        public virtual ICollection<equipment> equipment { get; set; }
    }
}
