//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentsWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public location()
        {
            this.facilities = new HashSet<facilities>();
            this.useraccounts = new HashSet<useraccounts>();
        }
    
        public string Address { get; set; }
        public int Postcode { get; set; }
        public string State { get; set; }
        public string Country_CountryName { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<facilities> facilities { get; set; }
        public virtual ICollection<useraccounts> useraccounts { get; set; }
    }
}
