//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentsWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions
    {
        public System.DateTime LoggedIn { get; set; }
        public Nullable<System.DateTime> LoggedOut { get; set; }
        public string UserAccounts_Email { get; set; }
    
        public virtual useraccounts useraccounts { get; set; }
    }
}
