//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentsWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccounts
    {
        public useraccounts()
        {
            this.facilities = new HashSet<facilities>();
            this.sessions = new HashSet<sessions>();
        }
    
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> Phone { get; set; }
        public string Location_Address { get; set; }
        public int Location_Postcode { get; set; }
        public string Location_Country_CountryName { get; set; }
    
        public virtual ICollection<facilities> facilities { get; set; }
        public virtual location location { get; set; }
        public virtual ICollection<sessions> sessions { get; set; }
    }
}
