//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentWebSCADA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class watermentdbEntities : DbContext
    {
        public watermentdbEntities()
            : base("name=watermentdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alarms> alarms { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<facilities> facilities { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<maintenance> maintenance { get; set; }
        public virtual DbSet<measurement> measurement { get; set; }
        public virtual DbSet<sessions> sessions { get; set; }
        public virtual DbSet<useraccounts> useraccounts { get; set; }
    }
}
