//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarms
    {
        public int Id { get; set; }
        public DateTime AlarmOccured { get; set; }
        public string Status { get; set; }
        public Nullable<float> ProcessValue { get; set; }
        public string Description { get; set; }
        public int equipment_Id { get; set; }
        public int equipment_facilities_Id { get; set; }
    
        public virtual equipment equipment { get; set; }
    }
}
