//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measurements
    {
        
        public int Id { get; set; }
        public Nullable<System.DateTime> Recorded { get; set; }
        public Nullable<float> ProcessValue { get; set; }
        public int equipments_Id { get; set; }
        public int equipments_facilities_Id { get; set; }
    
        public virtual equipments equipments { get; set; }
    }
}
