//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatermentWebSCADA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> LoggedIn { get; set; }
        public Nullable<System.DateTime> LoggedOut { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
